# Generated by Django 2.1.5 on 2019-02-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190205_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(blank=True, choices=[('تهران', 'تهران')], max_length=50),
        ),
    ]
