# Generated by Django 2.1.5 on 2019-02-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_house_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='space',
            field=models.IntegerField(default=0),
        ),
    ]
