# Generated by Django 2.2.1 on 2019-05-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190206_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, choices=[('تهران', 'تهران'), ('اراک', 'اراک'), ('سنندج', 'سنندج'), ('یاسوج', 'یاسوج'), ('بوشهر', 'بوشهر'), ('جم', 'جم'), ('اصفهان', 'اصفهان'), ('تبریز', 'تبریز'), ('قزوین', 'قزوین'), ('مشهد', 'مشهد'), ('ساری', 'ساری'), ('بیرجند', 'بیرجند'), ('زاهدان', 'زاهدان'), ('کرمان', 'کرمان'), ('زابل', 'زابل'), ('اهواز', 'اهواز'), ('آبادان', 'آبادان'), ('قم', 'قم'), ('کرمانشاه', 'کرمانشاه'), ('ایلام', 'ایلام'), ('ساوه', 'ساوه'), ('قائن', 'قائن'), ('قوچان', 'قوچان'), ('یزد', 'یزد'), ('شیراز', 'شیراز'), ('رشت', 'رشت'), ('شهرکرد', 'شهرکرد'), ('طبس', 'طبس'), ('نیشابور', 'نیشابور'), ('ری', 'ری'), ('کرج', 'کرج'), ('سمنان', 'سمنان'), ('شاهرود', 'شاهرود'), ('سبزوار', 'سبزوار')], max_length=50)),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, choices=[('تهران', 'تهران'), ('اراک', 'اراک'), ('سنندج', 'سنندج'), ('یاسوج', 'یاسوج'), ('بوشهر', 'بوشهر'), ('جم', 'جم'), ('اصفهان', 'اصفهان'), ('تبریز', 'تبریز'), ('قزوین', 'قزوین'), ('مشهد', 'مشهد'), ('ساری', 'ساری'), ('بیرجند', 'بیرجند'), ('زاهدان', 'زاهدان'), ('کرمان', 'کرمان'), ('زابل', 'زابل'), ('اهواز', 'اهواز'), ('آبادان', 'آبادان'), ('قم', 'قم'), ('کرمانشاه', 'کرمانشاه'), ('ایلام', 'ایلام'), ('ساوه', 'ساوه'), ('قائن', 'قائن'), ('قوچان', 'قوچان'), ('یزد', 'یزد'), ('شیراز', 'شیراز'), ('رشت', 'رشت'), ('شهرکرد', 'شهرکرد'), ('طبس', 'طبس'), ('نیشابور', 'نیشابور'), ('ری', 'ری'), ('کرج', 'کرج'), ('سمنان', 'سمنان'), ('شاهرود', 'شاهرود'), ('سبزوار', 'سبزوار')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='rent',
            name='house',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Provider'),
        ),
    ]
