# Generated by Django 2.2.1 on 2019-05-23 23:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190523_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('total_price', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SellInvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_invoice', to='main.SellInvoice')),
                ('number', smart_selects.db_fields.ChainedForeignKey(chained_field='product', chained_model_field='number', on_delete=django.db.models.deletion.CASCADE, related_name='item_number', to='main.Product')),
                ('price', smart_selects.db_fields.ChainedForeignKey(chained_field='product', chained_model_field='price', on_delete=django.db.models.deletion.CASCADE, related_name='item_price', to='main.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_product', to='main.Product')),
            ],
        ),
    ]
