# Generated by Django 2.0 on 2019-05-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190523_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevelOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('off', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='off',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellinvoiceitems',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellinvoiceitems',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
